# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[dev]
[dev.global.parameters]
stack_name = "ldnprj31-dev"
#template_file = "template-dev.yaml"

[dev.build.parameters]
region="us-east-1"
#stack_name = "ldnprj31-dev"
#s3_bucket = "mingzhoubucket"
cached = true
parallel = true
debug=true
#skip_pull_image=true
use_container=false

[dev.package.parameters]
region="us-east-1"
force_upload = true
s3_bucket = "mingzhoubucket"
#stack_name = "ldnprj31-dev"
output_template_file = "packaged.yaml"

[dev.deploy.parameters]
region="us-east-1"
s3_bucket = "mingzhoubucket"
#stack_name = "ldnprj31-dev"
capabilities="CAPABILITY_IAM"
#s3_prefix = "ldnprj31-dev"
disable_rollback = true
debug = true
force_upload = true
confirm_changeset = false
fail_on_empty_changeset = false

[dev.sync.parameters]
watch = true

[dev.local_start_api.parameters]
warm_containers = "EAGER"

[dev.local_start_lambda.parameters]
warm_containers = "EAGER"

#============================================

[prod]
[prod.build.parameters]
region="us-east-1"
stack_name = "ldnprj31-prod"
#s3_bucket = "mingzhoubucket"
template_file = "template-prod.yaml"
cached = true
parallel = true
debug=true
skip_pull_image=true
use_container=false

[prod.package.parameters]
region="us-east-1"
force_upload = true
s3_bucket = "mingzhoubucket"
stack_name = "ldnprj31-prod"
output_template_file = "packaged.yaml"

[prod.deploy.parameters]
region="us-east-1"
s3_bucket = "mingzhoubucket"
stack_name = "ldnprj31-prod"
template_file = "template-prod.yaml"
capabilities="CAPABILITY_IAM"
#s3_prefix = "ldnprj31-prod"
disable_rollback = true
debug = true
force_upload = true
confirm_changeset = false
fail_on_empty_changeset = false

[default]
[default.global.parameters]
stack_name = "ldnprj31"
s3_bucket = "mingzhoubucket"

[default.build.parameters]
cached = true
parallel = true
debug=true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
debug = true
force_upload = true
fail_on_empty_changeset = false

[default.package.parameters]
#resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
